trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git fetch https://github.com/doamatto/Simply.JS.git
    echo Fetched GitHub repo.
    ./compile-all.sh
  displayName: 'Compile Full Library'
